###

GET https://tx-email.devl.medigy.com/health

###

POST https://tx-email.devl.medigy.com/transform HTTP/1.1
Content-Type: application/json

{
    "templateIdentity": "create-password",
    "content": {
        "badData": 1
    }
}

###

GET http://localhost:8179/health

###

curl http://localhost:8179/transform/mod_test.single-tmpl.ts?body=TestBody&heading=TestHeading

### 

POST http://localhost:8179/transform HTTP/1.1
Content-Type: application/json

{
    "templateName": "medigy-email",
    "templateIdentity": "create-password",
    "content": {
        "badData": 1
    }
}
